spring:
  datasource:
    url: jdbc:postgresql://db.agmxrfatdspwshakdptw.supabase.co:5432/postgres
    username: postgres
    password: teamb03!project!!


auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168